apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/gcp-devops-415915/locations/us-central1-c/clusters/dev-cluster

